"""Shared, single-source implementations used by every tool in the toolkit.

Import from the submodules (``organize.core.report``) or from this package
directly — the names re-exported here are the ones the tools actually use.

Membership rule: a helper belongs here when more than one tool needs it *and*
its behaviour must not differ between them. Anything a single tool owns stays
in that tool.
"""

from __future__ import annotations

from .config import (
    ENV_FILE_NAME,
    LEGACY_LIBRARY_ENV_VAR,
    LIBRARY_ENV_VAR,
    default_library_root,
    default_reports_root,
    default_tool_dir,
    describe_library_origin,
    load_dotenv,
    resolve_library,
)
from .console import enable_utf8_stdio, print_text
from .fsio import atomic_write_text, path_is_within, path_norm, sha256_file
from .locking import (
    STANDARDIZER_LOCK_NAME,
    CoordinationLock,
    ExclusiveRunLock,
    LockTimeoutError,
    LockUnavailable,
    try_file_lock,
)
from .parallel import (
    DEFAULT_WORKER_CAP,
    JobOutcome,
    describe_workers,
    iter_completed,
    map_ordered,
    resolve_workers,
)
from .probecache import MediaProbeCache
from .ratelimit import BucketRegistry, TokenBucket, host_key
from .report import Report
from .runlog import RunLog
from .smoke import run_field_smoke_test
from .state import (
    KIND_BITDEPTH,
    KIND_LAYOUT,
    KIND_REMUX,
    KIND_SUBTITLE,
    KIND_SYNC,
    KINDS,
    STATE_DB_NAME,
    NullStateStore,
    StateStore,
    StoredMovie,
    Verdict,
    default_state_db,
    open_state,
    state_disabled_by_env,
)
from .subtitles import (
    COVERING_ENGLISH_SRT_SUFFIXES,
    EXTERNAL_SRT_CUE_RE,
    EXTERNAL_SRT_ENCODINGS,
    EXTERNAL_SRT_LANG,
    EXTERNAL_SRT_MAX_BYTES,
    EXTERNAL_SRT_SUFFIX,
    LEGACY_EXTERNAL_SRT_SUFFIX,
    decode_srt_bytes,
    exact_external_english_srt_path,
    legacy_external_english_srt_path,
    normalize_srt_newlines,
    promote_legacy_external_english_srt,
    srt_looks_valid,
    validate_srt_sidecar,
)
from .text import (
    REPORT_INDENT,
    REPORT_MIN_WIDTH,
    REPORT_WIDTH,
    clip_text,
    wrap_path_text,
    wrap_text,
)
from .toolchain import (
    PREREQUISITES,
    SCRAPING_DAILY_CAP,
    STEP_BINARIES,
    STEP_ORDER,
    STEPS,
    TOOL_SCRIPTS,
    TOOLS_DIR,
    Step,
    api_key_present,
    build_step_args,
    detect_tools,
    ffmpeg_installed,
    ffprobe_installed,
    ffsubsync_installed,
    ffsubsync_ready,
    missing_tool_scripts,
    mkvmerge_installed,
    prerequisite_issue,
    step_skip_reason,
)

__all__ = [
    "COVERING_ENGLISH_SRT_SUFFIXES",
    "KINDS",
    "KIND_BITDEPTH",
    "KIND_LAYOUT",
    "KIND_REMUX",
    "KIND_SUBTITLE",
    "KIND_SYNC",
    "STATE_DB_NAME",
    "NullStateStore",
    "StateStore",
    "StoredMovie",
    "Verdict",
    "default_state_db",
    "open_state",
    "state_disabled_by_env",
    "DEFAULT_WORKER_CAP",
    "JobOutcome",
    "describe_workers",
    "iter_completed",
    "map_ordered",
    "resolve_workers",
    "PREREQUISITES",
    "SCRAPING_DAILY_CAP",
    "STEPS",
    "STEP_BINARIES",
    "STEP_ORDER",
    "TOOLS_DIR",
    "TOOL_SCRIPTS",
    "Step",
    "api_key_present",
    "build_step_args",
    "detect_tools",
    "ffmpeg_installed",
    "ffprobe_installed",
    "ffsubsync_installed",
    "ffsubsync_ready",
    "missing_tool_scripts",
    "mkvmerge_installed",
    "prerequisite_issue",
    "step_skip_reason",
    "ENV_FILE_NAME",
    "EXTERNAL_SRT_CUE_RE",
    "EXTERNAL_SRT_ENCODINGS",
    "EXTERNAL_SRT_LANG",
    "EXTERNAL_SRT_MAX_BYTES",
    "EXTERNAL_SRT_SUFFIX",
    "LEGACY_EXTERNAL_SRT_SUFFIX",
    "LEGACY_LIBRARY_ENV_VAR",
    "LIBRARY_ENV_VAR",
    "REPORT_INDENT",
    "REPORT_MIN_WIDTH",
    "REPORT_WIDTH",
    "STANDARDIZER_LOCK_NAME",
    "CoordinationLock",
    "ExclusiveRunLock",
    "LockTimeoutError",
    "LockUnavailable",
    "BucketRegistry",
    "MediaProbeCache",
    "TokenBucket",
    "host_key",
    "Report",
    "RunLog",
    "atomic_write_text",
    "clip_text",
    "decode_srt_bytes",
    "default_library_root",
    "default_reports_root",
    "default_tool_dir",
    "describe_library_origin",
    "enable_utf8_stdio",
    "exact_external_english_srt_path",
    "legacy_external_english_srt_path",
    "load_dotenv",
    "normalize_srt_newlines",
    "path_is_within",
    "path_norm",
    "print_text",
    "promote_legacy_external_english_srt",
    "resolve_library",
    "run_field_smoke_test",
    "sha256_file",
    "srt_looks_valid",
    "try_file_lock",
    "validate_srt_sidecar",
    "wrap_path_text",
    "wrap_text",
]
